#!/usr/bin/env bash
# bash script that display best school 10 times with the tenth element being Hi

x=1
while [ $x -le 10 ]
do 
	echo "Best School"
	if [ $x -eq 9 ]
	then
		echo "Hi"
	fi
	((x++))
done
