#!/usr/bin/env bash
#Script to loop from 1 - 10
# 4th position - bad luck
# 8th position - good luck
# other position - Best school

x=1
while [ $x -le 10 ]
do 
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
