#!/usr/bin/env bash
#a script to print information about a file

file="School"
if [ -a $file ]
then
	echo "school file exit"
	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exit"
fi
